makimoch/chapter2/2-3.rb
makimoch/chapter2/2-6.rb
makimoch/chapter2/2-7.rb

第２章提出します。プルリク練習のため、章別にブランチ切って提出していきたいと思います。ご面倒かもしれませんが、よろしくお願いいたします。

課題提出<makimoch> 第2章

---

rines/chapter7/1.rb
rines/chapter7/2.rb
rines/chapter7/3.rb
rines/chapter7/4.rb
rines/chapter7/5.rb
rines/chapter7/6.rb
rines/chapter7/7.rb
rines/chapter7/8.rb
rines/chapter7/9.rb

先週は分量が多かったのでまとめてPRに出していましたが、今回はちゃんと章ごとに提出します。
よろしくお願いします。

課題提出 rines 第7章

---

rines/chapter9/1.rb
rines/chapter9/2.rb
rines/chapter9/3.rb
rines/chapter9/4.rb
rines/chapter9/whipped_cream.rb

課題提出 rines 第9章

---

hirok803/chapter7/7-1.rb
hirok803/chapter7/7-2.rb
hirok803/chapter7/7-3.rb
hirok803/chapter7/7-4.rb
hirok803/chapter7/7-5.rb
hirok803/chapter7/7-6.rb
hirok803/chapter7/7-7.rb
hirok803/chapter7/7-8.rb
hirok803/chapter7/7-9.rb

課題提出 hirok803 第7章

---

yazawa8/chapter7/7-1.rb
yazawa8/chapter7/7-2.rb
yazawa8/chapter7/7-3.rb
yazawa8/chapter7/7-4.rb
yazawa8/chapter7/7-5.rb

yazawa 課題提出 chapter7

---

yazawa8/chapter8/8-1.rb
yazawa8/chapter8/8-2.rb
yazawa8/chapter8/8-3.rb
yazawa8/chapter8/8-4.rb
yazawa8/chapter8/8-5.rb
yazawa8/chapter8/8-6.rb
yazawa8/chapter8/8-7.rb

yazawa 課題提出 chapter8

---

makimoch/chapter7/3.rb
makimoch/chapter7/5.rb
makimoch/chapter7/8.rb

この辺りから、問題の意図する日本語が難しくなっているのを感じます。。。そもそも日本語を読み違えていることがあったり、習った言葉の定義が自分のなかでもあやふやなので、何をどうしたら正解なのかを整理するところからやっています。
今回、インデントは注意したつもりです。。。インデントのチェックも慣れが必要かと思いますが、そこにリソース割かなくてもいいって考え方もあるので、rufo入れようか迷ってます。

課題提出 makimoch 第7章

---

makimoch/chapter7/3.rb
makimoch/chapter7/5.rb
makimoch/chapter7/8.rb
makimoch/chapter8/5.rb
makimoch/chapter8/7.rb
makimoch/chapter8/9.rb

よろしくお願いします！
いつもと同じように作業したつもりですが、今回のプルリクだけchapter7のブランチの作業が一緒に入ってるみたいです。なにか操作を誤ったのでしょうか・・・。ローカルのtigを見ても、コミットはそれぞれのブランチで1回ずつです。なぜリモートのchapter8のブランチにコミットが2つあるのか不明でした。
```
2019-06-29 19:50 +0900 makimoch    o [makimoch-chapter8] {origin/makimoch-chapter8} chapter8提出します
2019-06-29 18:54 +0900 makimoch    o [makimoch-chapter7] {origin/makimoch-chapter7} chapter7提出します
2019-06-25 13:02 +0900 makimoch    o [makimoch-chapter5] {origin/makimoch-chapter5} 不要なコメントを削除
```

課題提出 makimoch 第8章

---

makimoch/chapter7/3.rb
makimoch/chapter7/5.rb
makimoch/chapter7/8.rb
makimoch/chapter8/5.rb
makimoch/chapter8/7.rb
makimoch/chapter8/9.rb
makimoch/chapter9/2.rb
makimoch/chapter9/3.rb
makimoch/chapter9/4-module.rb
makimoch/chapter9/4.rb

課題提出します。
所感として、8章以降はひたすらコード書いて慣れが必要かなと思っています。8章以降出てきた色々な処理の方法やテクニックについて読んで書いて理解できましたが、使える手応えがないなぁという感じです。自分でもっといろいろ書いてみてから遠回りした後に、「そう言えば便利な方法があるんだった！」って戻ってくると一番しっくりくる気がします。こういうのって使い所を事前に学んで知っていてもなかなか使えるようにならないのが、難しいです。

課題提出 makimoch 第9章

---

yazawa8/chapter9/9-1.rb
yazawa8/chapter9/9-2.rb
yazawa8/chapter9/9-3-module.rb
yazawa8/chapter9/9-3.rb

課題提出 chapter9 yazawa8

---

hirok803/chapter10/10-1.rb
hirok803/chapter10/10-2.rb
hirok803/chapter10/10-3.rb

課題提出 hirok803 第10章

---

yazawa8/chapter10/10-2.rb
yazawa8/chapter10/10-3.rb
yazawa8/chapter10/sinatra-drink.rb
yazawa8/chapter10/sinatra-hi.rb

課題提出 chapter10 yazawa8

---

hirok803/chapter7/7-1.rb
hirok803/chapter7/7-2.rb
hirok803/chapter7/7-3.rb
hirok803/chapter7/7-4.rb
hirok803/chapter7/7-5.rb
hirok803/chapter7/7-6.rb
hirok803/chapter7/7-7.rb
hirok803/chapter7/7-8.rb
hirok803/chapter7/7-9.rb
hirok803/chapter8/8-1.rb
hirok803/chapter8/8-2.rb
hirok803/chapter8/8-3.rb
hirok803/chapter8/8-4.rb
hirok803/chapter8/8-5.rb
hirok803/chapter8/8-6.rb
hirok803/chapter8/8-7.rb
hirok803/chapter8/8-8.rb
hirok803/chapter8/8-9.rb

課題提出 hirok803 第8章

---

hirok803/chapter9/9-1.rb
hirok803/chapter9/9-2.rb
hirok803/chapter9/9-3.rb
hirok803/chapter9/9-4-WC.rb
hirok803/chapter9/9-4.rb

確認お願いします
Rufo　インストールしたけど、まだ動作できてないようです。Vscodeの設定したけど。
継続調査中

課題提出 hirok803 第9章

---

rines/chapter8/1.rb
rines/chapter8/2.rb
rines/chapter8/3.rb
rines/chapter8/4.rb
rines/chapter8/5.rb
rines/chapter8/6.rb
rines/chapter8/7.rb
rines/chapter8/8.rb
rines/chapter8/9.rb

課題提出 rines 第8章

---

nakashima/chapter10/1.rb
nakashima/chapter10/2.rb
nakashima/chapter10/3.rb
nakashima/chapter10/sinatra_drink.rb
nakashima/chapter10/sinatra_hi.rb

課題提出 nakashima 10章

---

aoronesy/chapter10/10-1.rb
aoronesy/chapter10/10-2.rb
aoronesy/chapter10/10-3.rb
aoronesy/chapter10/Gemfile
aoronesy/chapter10/Gemfile.lock

課題提出 aoronesy 第10章

---

nmitsuda/chapter9/9-1.rb
nmitsuda/chapter9/9-2.rb
nmitsuda/chapter9/9-3.rb
nmitsuda/chapter9/9-4.rb
nmitsuda/chapter9/9-4_2.rb

超入門課題提出nmitsuda第９章

---

OTA88/chapter8/8-7.rb
OTA88/chapter8/8-9.rb

課題提出 OTA88 第8章

---

OTA88/chapter9/9-2.rb
OTA88/chapter9/9-4.rb
OTA88/chapter9/whipped_cream.rb

課題提出 OTA88 第9章

---

OTA88/chapter10/10-1.rb
OTA88/chapter10/10-2.rb
OTA88/chapter10/10-3.rb

課題提出 OTA88 第10章

---

Suwazono01/chapter10/10-2.rb
Suwazono01/chapter10/10-3-2.rb
Suwazono01/chapter10/10-3.rb
Suwazono01/chapter10/Gemfile
Suwazono01/chapter10/Gemfile.lock
Suwazono01/chapter10/sinatra_drink.rb
Suwazono01/chapter10/sinatra_hi.rb

いまいち自信がありませんが、確認お願いします。
自分のPCでアプリを起動している際にPCからサイトにアクセスするにはどうしたら良いでしょうか…

課題提出　Suwazono01　第10章

---

Suwazono01/chapter6/6-1.rb
Suwazono01/chapter6/6-2.rb
Suwazono01/chapter6/6-3.rb
Suwazono01/chapter7/7-1.rb
Suwazono01/chapter7/7-2.rb
Suwazono01/chapter7/7-3.rb

課題提出 Suwazono01 第7章
